web:
  image: {{WEB_IMAGE}}
  volumes:
    - ./app:/var/www/html
  links:
    - db:db
  environment:
    VIRTUAL_HOST: {{HOST}},www.{{HOST}}

db:
  image: mysql:5.6
  volumes:
    - ./docker/database:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

db_web_admin:
  image: nazarpc/phpmyadmin
  links:
    - db:mysql
  environment:
      VIRTUAL_HOST: phpmyadmin.{{HOST}}
